/*

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

Answer: 4613732

*/
package main

import "fmt"

func main() {
  sum := 0

  f := fib()

  for {
    n := f()

    if n > 4000000 {
      break
    }

    if n % 2 == 0 {
      sum += n
    }
  }

  fmt.Println(sum)
}

func fib() func() int {
  a, b := 0, 1

  return func() int {
    a, b = b, a+b
    return a
  }
}
